version: '3'

services:
  nodejs-app:
    build: .
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs-app